// GENERATED by scripts/generate-runtime-env.mjs before every build — do not
// edit by hand and do not import anywhere except app.config.ts. The committed
// version carries the local-dev default.
export const RUNTIME_API_BASE_URL = 'https://clapout-backend.vercel.app/api/v1';
